version: 2
jobs:
  publish:
    docker:
      - image: circleci/python:3
    steps:
      - attach_workspace:
          at: ./
      - setup_remote_docker:
          docker_layer_caching: true
      - checkout
      - run: curl https://raw.githubusercontent.com/MVPStudio/build_setup/master/build_tag_push.sh | bash

workflows:
  version: 2
  build-publish-deploy:
    jobs:
      - publish:
          context: dockerhub-publish
          filters:
            branches:
              only: master